name: Android CI Build

on:
  push:
    branches: [ "main" ] # Or your primary branch, e.g., master
  pull_request:
    branches: [ "main" ] # Or your primary branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Common version for modern Android, adjust if needed
        distribution: 'temurin' # Popular OpenJDK distribution
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew # Assuming gradlew is in the root directory

    - name: Build with Gradle
      run: ./gradlew assembleDebug # Builds a debug APK. Use assembleRelease for release.

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk # Standard path for debug APK
